### ISSUE TITLE
github event 를 이용해 issue close 시 WORKING label 제거

### ISSUE THREAD

**Issue by alkee-allm** [alkee-allm/k2proto#44]
[working label](https://github.com/alkee-allm/k2proto/issues?q=is%3Aissue+label%3AWORKING)을 이용해 해당 issue 가 진행중임을 표시하고, issue 가 close 될 때 [workflow events](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#external-events-repository_dispatch)를 통해 자동으로 이 label 이 제거되도록.

참고 : [Github Action 사용법 정리](https://zzsza.github.io/development/2020/06/06/github-action/)

**Comment by alkee-allm** [comment]
[Action Remove Labels](https://github.com/marketplace/actions/actions-ecosystem-remove-labels) 이 github marketplace 에 등록되어있으니, [테스트 rpository](https://github.com/alkee-allm/githubaction)를 만들어 실험해보자.

**Comment by alkee-allm** [comment]
`.github/workflows/blank.yml` 파일 작성
```yaml
name: label test
on:
  issues:
    types: [closed]
    
jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.github_token }}
          labels: documentation
          number: ${{ issue.number }}
```
`number: ${{ issue.number }}` 는 뇌피셜. 지정된 issue 번호를 알아야 하는데.. reference 를 못찾겠다.

일단 test issue 를 하나 만들어 close 해보니 아무 반응 없다. [action 의 result 확인](https://github.com/alkee-allm/githubaction/actions)해보니, 

![image](https://user-images.githubusercontent.com/49409045/91662258-2c1e0d00-eb1c-11ea-8bde-c25dde79b5d0.png)

역시나 `${{ isssue.number }}` 문제인 듯

**Comment by alkee-allm** [comment]
[googling](https://github.com/actions/toolkit/issues/289) 을 통해 `${{ github.context.issue.number }}` 와 같이 변경해 작업 성공.

![image](https://user-images.githubusercontent.com/49409045/91662512-e104f980-eb1d-11ea-8da6-5fff4335e95e.png)

![image](https://user-images.githubusercontent.com/49409045/91662517-ec582500-eb1d-11ea-842c-8d721d7a9bc4.png)

**Comment by alkee-allm** [comment]
https://github.com/alkee-allm/k2proto/commit/bf2d6a4f245586b6fd71da700bc580a1a4c94b45 에 workflow 추가

**Comment by alkee-allm** [comment]
![image](https://user-images.githubusercontent.com/49409045/91663715-96877b00-eb25-11ea-8991-ff7ee6741287.png)

label 을 `documentaion`(테스트에서 사용했던 label 이름) 이라고 해 오류. `WORKING` 이라고해야하는데... 

그보다, 올바르게 label 을 지정하더라도 **해당 라벨이 issue 에 지정되지 않았을 경우 항상 오류 로그**가 남게 될 것.

찝찝하다... 수정해보자.

**Comment by alkee-allm** [comment]
[github action 에서 사용할 수 있는 function](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#functions)과 [label 의 사용 예](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#example-using-an-array)를 이용해 조건(condition)화 할 필요가 있을 것.

**Comment by alkee-allm** [comment]
`WORKING` label 이 제거되고 나서 close 되면 어떤 오류가 남는지 확인

현재상태
![image](https://user-images.githubusercontent.com/49409045/91664309-4c07fd80-eb29-11ea-9642-abe84a487c21.png)

**Comment by alkee-allm** [comment]
이미 label 이 제거되고 나서도 오류없이 올바르게 action 동작이 이루어짐을 확인.

![image](https://user-images.githubusercontent.com/49409045/91664336-7d80c900-eb29-11ea-8b82-50804756841d.png)

**Comment by alkee-allm** [comment]
https://github.com/alkee-allm/k2proto/commit/da7869daf42dfd1c2d68f03031f05f7ff5e677b0 에 수정 반영.

[`issue-working-level-remove.yml`](https://github.com/alkee-allm/k2proto/blob/da7869daf42dfd1c2d68f03031f05f7ff5e677b0/.github/workflows/issue-working-level-remove.yml)

```yml
# https://github.com/alkee-allm/k2proto/issues/44

name: WORKING issue label remover

on:
  issues:
    types: [closed]
    

jobs:
  remove_label: # https://github.com/marketplace/actions/actions-ecosystem-remove-labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ contains(github.event.issue.labels.*.name, 'WORKING') }}
        with:
          github_token: ${{ secrets.github_token }}
          labels: WORKING
          number: ${{ github.context.issue.number }}
```
